name: Java Maven CI

# Run this workflow when pushing to the main branch or opening a pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (You can specify a different version of JDK if required)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # You can specify your required Java version here



      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn -B clean install  # 'mvn -B' runs in batch mode (non-interactive)

      # Step 5: Run unit tests (optional, happens during 'install' phase by default)
      - name: Run tests
        run: mvn test